### ISSUE TITLE
REQUEST FAILED WITH STATUS CODE 500

### ISSUE THREAD

**Issue by 0xOzgur** [sametatasever/etb-projects-voting-app#2]
Hi samet,
When I run dev I have an error like that. 
What is wrong with me =)

![image](https://user-images.githubusercontent.com/29779769/134806060-eac0f8fc-bca4-4b53-8f30-0d5519c820d7.png)

**Comment by 0xSamet** [comment]
Merhaba, bir video çekmiştim göndereyim ordan ilerleyebilirsiniz.
https://we.tl/t-Lgr4Lom80T

Ozgur Uzden ***@***.***>, 26 Eyl 2021 Paz, 14:39 tarihinde
şunu yazdı:

**Comment by 0xOzgur** [comment]
Çok teşekkürler, inceleyip bilgi vereceğim.

**Comment by 0xOzgur** [comment]
Teşekkürler, bu video sorunu çözdü. Boş bir zamanında dökümantasyonu konusunda yardımcı olmaya çalışacağım :)

**Comment by 0xSamet** [comment]
Saolun dokümantasyon yazmak lazım :)

Ozgur Uzden ***@***.***>, 26 Eyl 2021 Paz, 15:18 tarihinde
şunu yazdı:
